name: ClusterFuzzLite
on:
  pull_request:
    paths:
      - 'c_src/**'
      - 'fuzz/**'
      - 'CMakeLists.txt'
  push:
    branches:
      - main
  schedule:
    # Run at 00:00 UTC daily
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
          - undefined
          - memory
    steps:
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          sanitizer: ${{ matrix.sanitizer }}
          language: c
          build-integration-path: ./fuzz/build.sh

      - name: Run Fuzzers (${{ matrix.sanitizer }})
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: 'code-change'
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true

      - name: Upload Crash
        # v4.3.3
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        if: failure() && steps.run.outcome == 'failure'
        with:
          name: ${{ matrix.sanitizer }}-artifacts
          path: ./out/artifacts

      - name: Upload SARIF
        if: always() && steps.run.outcome == 'success'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./out/results.sarif
          category: clusterfuzzlite-${{ matrix.sanitizer }}

  Batch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address
    steps:
      - name: Build Fuzzers (${{ matrix.sanitizer }})
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          sanitizer: ${{ matrix.sanitizer }}
          language: c
          build-integration-path: ./fuzz/build.sh

      - name: Run Fuzzers (${{ matrix.sanitizer }})
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 3600
          mode: 'batch'
          sanitizer: ${{ matrix.sanitizer }}

      - name: Upload Crash
        # v4.3.3
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        if: failure() && steps.run.outcome == 'failure'
        with:
          name: ${{ matrix.sanitizer }}-batch-artifacts
          path: ./out/artifacts

  Prune:
    runs-on: ubuntu-latest
    steps:
      - name: Build Fuzzers (address)
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          sanitizer: address
          language: c
          build-integration-path: ./fuzz/build.sh

      - name: Minimize Corpus
        id: prune
        uses: google/clusterfuzzlite/actions/prune@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
